version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nestjs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestjs_user -d nestjs_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nestjs_user
      DATABASE_PASSWORD: nestjs_password
      DATABASE_NAME: nestjs_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nestjs-network

volumes:
  postgres_data:

networks:
  nestjs-network:
    driver: bridge